# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji


# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: /page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: splashpad4ely # jekyll-seo-tag > Owners twitter username
author: Bryony Braschi # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Bryony Braschi # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/splashpad4ely

service_worker: false
css_inline: true

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: "........" # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# # 5. Collections
# collections:
#   posts:
#     title: Blog posts from the HGNC and VGNC # Needed for Siteleaf
#     output: true
#    # description: "Blog posts from the HGNC and VGNC" # The post list page content
#     # feature_image: "/blog/images/wordcloud.png"

# # 6. Jekyll collections settings
# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       feature_image: "/blog/images/wordcloud.png"

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Splash Pad For Ely" # Site name or title, also used in jekyll-seo-tag
logo: "/images/" # Site logo, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag
url: "https://splashpad4ely.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
excerpt_separator: "........"
repo: "https://github.com/splashpad4ely/splashpad4ely-website"
email: "splashpad4ely@gmail.com"
# disqus: "hgnc-and-vgnc-blog.disqus.com/embed.js" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/images/favicon.ico" 
google_analytics: 'UA-33040314-6'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  HGNC: https://www.genenames.org
  VGNC: https://vertebrate.genenames.org
  #Elements: /elements/
  #Blog: /blog/
  #Categories: /categories/
  Search: /search/


navigation_footer:
  Created by HGNC and VGNC team: https://www.genenames.org/about/team/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/genenames
  GitHub: https://github.com/HGNC
  YouTube: https://www.youtube.com/channel/UCqGBx2FrgmeXlbeRTCkvI3g
  email: https://www.genenames.org/contact/feedback/
  YouTube: https://www.youtube.com/channel/UCqGBx2FrgmeXlbeRTCkvI3g
  # link: https://www.genenames.org
  # link2: https://vertebrate.genenames.org 
  #RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: ""

sass:
    sass_dir: assets/_sass
    style: compressed
